### ISSUE TITLE
Languages support

### ISSUE THREAD

**Issue by Mte90** [shahbaz17/privacyMonth2017#1]
In our case we want in Italian, so maybe like a subfolder where we can put the text in Italian and the image in overlay in Italian will be amazing!

**Comment by shahbaz17** [comment]
Sure i'll put the whole thing in a folder and when clicked on Italian language. It will redirected to that page with italian overlay image. Else you can submit your PR with the changes

**Comment by shahbaz17** [comment]
Send me the overlay image and localized text for the website. I'll put it for you

**Comment by shahbaz17** [comment]
Its live now.
Visit http://privacymonth2017.online/ITA/

**Comment by shahbaz17** [comment]
Can you review https://github.com/shahbaz17/privacyMonth2017/pull/7 ?

**Comment by shahbaz17** [comment]
Fixed
