### ISSUE TITLE
Add German support

### ISSUE THREAD

**Issue by Ryuno-Ki** [shahbaz17/privacyMonth2017#10]
As offered on Telegram I'm translating the site into German.

**Comment by shahbaz17** [comment]
So is the PR ready ?

**Comment by Ryuno-Ki** [comment]
The only thing missing is an updated showcase image.

@TitanNano was so kind to run the FB code for me.
![photo_2017-01-08_11-30-15](https://cloud.githubusercontent.com/assets/3097194/21749058/f6c1c1aa-d595-11e6-9855-839247165b87.jpg)
is what I got. It looks like I missed something …

**Comment by shahbaz17** [comment]
Merged https://github.com/shahbaz17/privacyMonth2017/pull/12
