### ISSUE TITLE
Split translated bits out of script.js

### ISSUE THREAD

**Issue by Ryuno-Ki** [shahbaz17/privacyMonth2017#13]
Currently there is a string in script.js which would need a translation: https://github.com/shahbaz17/privacyMonth2017/blob/758ac86d880d1b0e396ab9a67dbb9bcbb1ea3c00/script.js#L15

I'd suggest to break it out of the file and move it into a separate one.
This way most of the logic could be shared among translations.

**Comment by shahbaz17** [comment]
Looks nice to me.
Can you submit a PR which will fix this ?

**Comment by Ryuno-Ki** [comment]
Of course. Will look into it this evening (= ~9 hours from now). Would be helpful to land #12 and #6 first.

**Comment by Ryuno-Ki** [comment]
Hm, looks more complicated then I thought. My first idea was to move the `loadPicture` function into a separate file. But it uses `loadOnCanvas`, so I likely need to move that as well. That function has several dependencies …

So the best way may be to put the string into a `data-*` attribute (slows the script a bit because of a walk to DOM land). Would that be fine?

**Comment by shahbaz17** [comment]
Will work on later.
Since the scope of this project is limited. Definitely would like to improve later on
