### ISSUE TITLE
The spanish example has an error

### ISSUE THREAD

**Issue by kurai021** [shahbaz17/privacyMonth2017#21]
the text "Se un maestro de la privacidad" has a little mistake, the text is "Sé un maestro de la privacidad" with accent mark in "Sé"

**Comment by shahbaz17** [comment]
Can you submit a PR for this ?

On Fri, Jan 13, 2017 at 8:55 AM, Richard Armuelles <notifications@github.com

**Comment by kurai021** [comment]
@edovio did not include the logo in a editable format

**Comment by edovio** [comment]
I fix immediately:) I'm sorry I don't put the .AI file but if you need I can put in my repository :)

**Comment by edovio** [comment]
Updated the file at this link: https://github.com/edovio/privacymonth2017graphics/blob/master/ES/logoNEW.png

**Comment by shahbaz17** [comment]
It's live now. But display pic as of now has the previous version.
I would request ES community to send me that pic with the latest overlay by generating it from the website.
Cheers,
Shahbaz

**Comment by kurai021** [comment]
done!
