### ISSUE TITLE
German page have problems

### ISSUE THREAD

**Issue by Mte90** [shahbaz17/privacyMonth2017#22]
The menu link have double EN and the avatar is Portuguese
http://privacymonth2017.online/DE-DE/

**Comment by shahbaz17** [comment]
Double EN is fixed. 
I don't have the german overlay image.
Waiting for that

**Comment by Ryuno-Ki** [comment]
As I said before, without the source code of the image, I couldn't update the image. I'll look into the double English thingy.

**Comment by Mte90** [comment]
I think that https://github.com/shahbaz17/privacyMonth2017/blob/master/ITA/logo.png with a little bit of photoshop (removing the text) is the simpliest solution.

**Comment by Ryuno-Ki** [comment]
I don't have Photoshop (or any other Adobe product).
Isn't there an .xcf (GIMP) file?

Concerning „said before”, see https://github.com/shahbaz17/privacyMonth2017/issues/10#issuecomment-271142650
