### ISSUE TITLE
Add pt-br lang

### ISSUE THREAD

**Issue by barrosgg** [shahbaz17/privacyMonth2017#3]

**Comment by barrosgeraldo** [comment]
All files: https://www.dropbox.com/sh/mreml73b9n4uq99/AACkSWnWyXOevv8T047Zm9KKa?dl=0

**Comment by shahbaz17** [comment]
Its live http://privacymonth2017.online/PT-BR/

**Comment by shahbaz17** [comment]
Hello @barrosgeraldo 
Can you review the translated text here https://github.com/shahbaz17/privacyMonth2017/pull/5

**Comment by barrosgg** [comment]
This text is perfect, thanks.

**Comment by shahbaz17** [comment]
@barrosgeraldo can you specify which is perfect ?
PR one or the latest running one

**Comment by barrosgg** [comment]
The latest running one.

**Comment by shahbaz17** [comment]
Thanks for reporting.
Closing this issue now.
Cheers
