### ISSUE TITLE
Add spanish support

### ISSUE THREAD

**Issue by kurai021** [shahbaz17/privacyMonth2017#6]
Hi, Can I help you? I could translate the site in neutral spanish (Latin America)

**Comment by shahbaz17** [comment]
Sure
Just create a sub-folder as ITA and change the texts wherever necessary

**Comment by edovio** [comment]
If you need I can help you to have an HQ Image for the translation :) let me know the localized test for the logo.png and I create for you :)

**Comment by shahbaz17** [comment]
Hey @kurai021 you can take help from @edovio for the HQ logo.
And thanks @edovio for the support. +1

**Comment by edovio** [comment]
@shahbaz17 if you prefeer the last one done for the English version too, let me know ;) I can prepare it in few seconds :)

**Comment by shahbaz17** [comment]
Go ahead and send me the pic.
And thank you :-)

On 04-Jan-2017 11:49 PM, "Edoardo Viola" <notifications@github.com> wrote:

@shahbaz17 <https://github.com/shahbaz17> if you prefeer the last one done
for the English version too, let me know ;) I can prepare it in few seconds
:)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/shahbaz17/privacyMonth2017/issues/6#issuecomment-270444715>,
or mute the thread

**Comment by kurai021** [comment]
Hi @edovio I need the logo translated to spanish, the text "Get Smart on Privacy", could be translated as "Se un Maestro de la Privacidad", the demo could be this image https://pbs.twimg.com/profile_images/529260455944937473/kBMBDdYM.jpeg

thank you for your support!

**Comment by kurai021** [comment]
ahh.. the demo is generated with the site, only need the logo.png

**Comment by edovio** [comment]
Do you prefeer that I create a pull request or do you prefeer to have only the png?

**Comment by edovio** [comment]
@kurai021 you can find the file here: https://github.com/edovio/privacymonth2017graphics/tree/master/ES

**Comment by edovio** [comment]
@shahbaz17 at this link you can find the file in English: https://github.com/edovio/privacymonth2017graphics/tree/master/EN

**Comment by kurai021** [comment]
@shahbaz17 could you give me write permissions?

**Comment by shahbaz17** [comment]
Hey @kurai021 
Write access for ?

**Comment by kurai021** [comment]
I have the spanish translation

**Comment by shahbaz17** [comment]
Can you do a PR for that

**Comment by kurai021** [comment]
OK, is ready :+1:

**Comment by shahbaz17** [comment]
PR merged https://github.com/shahbaz17/privacyMonth2017/pull/19
